apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app2
  name: busybox-cephfs-pvc-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName:  ocs-external-storagecluster-cephfs
