apiVersion: v1                    
kind: Namespace
metadata:
  name: cnv-sub-1    
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cnv-sub-1
  namespace: cnv-sub-1
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - cnv-sub-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-parikshithb-ocs-workloads-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-parikshithb-ocs-workloads
  namespace: ggithubcom-parikshithb-ocs-workloads-ns
spec:
  type: Git
  pathname: 'https://github.com/parikshithb/ocs-workloads.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: cnv-workload
    apps.open-cluster-management.io/git-path: mdr/cnv-workload/vm-resources
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: cnv-sub-1
  name: cnv-sub-1-subscription-1
  namespace: cnv-sub-1
spec:
  channel: ggithubcom-parikshithb-ocs-workloads-ns/ggithubcom-parikshithb-ocs-workloads
  placement:
    placementRef:
      kind: Placement
      name: cnv-sub-1-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: cnv-sub-1
  name: cnv-sub-1-placement-1
  namespace: cnv-sub-1
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'name'
              operator: 'In'
              values: 
                - 'PLACEHOLDER'
  clusterSets:
    - global
