apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app5
  name: busybox-rbd-pvc-5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
